server:  
  port: 8070
logging:
  config: classpath:log4j2.yaml
spring:
  redis:
    database: 0
    host: 11111
    password: 111
    port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:/public/thymeleaf/
licc:
  users:
    - name: 111
      cookie: 111
    - name: 111
      cookie: 1111

  petUrl: https://pet-chain.baidu.com/











