server:  
  port: 8070
logging:
  config: classpath:log4j2.yaml
spring:
  redis:
    database: 0
    host: 47.94.196.111
    password: 5998012
    port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:/public/thymeleaf/
licc:
  users:
    - name: licc168
      cookie: PSTM=1508996024; BIDUPSID=63D0C1A4224F939838EA8F27215B7AF5; BAIDUID=AE34FC22B63302BDF0D6E662ACD63491:FG=1; MCITY=-179%3A; FP_UID=56d298c273023bea8e2f2676e91c0d86; BDUSS=NzfkptMlZjZ2NXdzJlNm9wcGlxdkJ6eWNTOURqSkc1S0JvN016Mk5WQUxkZGxhQVFBQUFBJCQAAAAAAAAAAAEAAADMKCUYbGljYzE2OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvosVoL6LFaaE; STOKEN=c531f523a5ce3c6e9807ea69a9807ec5113a61f42b00883a4fc1fbad5caf73e6
    - name: 13247002545
      cookie: BAIDUID=4AFA9A762CA70F37E98B93972950A485:FG=1; FP_UID=6678d813aa1b981dbac44bca2bdfd97f; BDUSS=N0RH5Hakw1dHFnOC01aWlMZWItTUYyemVrTng3ZU4wY3BWaGVtczFDY0VsdEZhQVFBQUFBJCQAAAAAAAAAAAEAAABvbJw00rvD68zUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQJqloECapaUF; STOKEN=3f9a56b7168040fe971d5a9926e566328c5f7ccfc9aa19d2ea72ad6cbccb017f
    - name: 13042026535
      cookie: BAIDUID=1BD7832341FA26976CC7279946DE1E80:FG=1; FP_UID=bf19f4a73ccc602eabb9e77a11c81458; BDUSS=TNmM0NNOXFTSX5Qc1pzRk9OT2hISENZQ3ZBYUx-NGZzUkxIODA3Wkx0bnRWTkZhQVFBQUFBJCQAAAAAAAAAAAEAAADStU8MX1RpbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO3HqVrtx6laa; STOKEN=291bf8b9619d7276fa447eb1f3d447ea7fbdbdb09ffe470266a19c02ab359bbd
    - name: 18380403376
      cookie: BAIDUID=186A1BF2DCD6C48EA62F2D3E86F1EA0C:FG=1; BIDUPSID=186A1BF2DCD6C48EA62F2D3E86F1EA0C; PSTM=1499219651; FP_UID=339a2bf3464147c9a61386589a7a4505; BDUSS=NkcU1xTFpOajQ0V01VZnU4M3FTdFM0aWY0NFNIfk9rTVFvODdYeXJjMnFHc2RhQVFBQUFBJCQAAAAAAAAAAAEAAABGXx06Q2hsb2VfSE0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKqNn1qqjZ9aR0; BDRCVFR[Fc9oatPmwxn]=srT4swvGNE6uzdhUL68mv3; PSINO=5; H_PS_PSSID=1461_21102_22157; locale=zh; STOKEN=cdf29af8690b211800f694e63376585d5e6f1312b63e1b028fa3869d134220ed

  petUrl: https://pet-chain.baidu.com/











